### ISSUE TITLE
Legacy role install fail

### ISSUE THREAD

**Issue by chouseknecht** [ansible/mazer#74]
##### GALAXY CLI VERSION
```
Ansible Galaxy CLI, version0.1.0
Darwin, cyclone.local, 17.6.0, Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64, x86_64
2.7.14 (default, Nov 14 2017, 23:24:24)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.38)]/Users/chouseknecht/.pyenv/versions/venv27/bin/python
Using /Users/chouseknecht/.ansible/mazer.yml as config file
```

##### CONFIGURATION
```
version: '1.0'
server:
  url: https://galaxy-qa.ansible.com
  ignore_certs: False

content_path: ~/.ansible/content
verbosity: 0
```

##### SUMMARY
Legacy role gets installed as `content/namespace.namespace.repo/roles/namespace.repo`

##### STEPS TO REPRODUCE
```bash
mazer install geerlingguy.apache
```
##### EXPECTED RESULTS
Role installed as `content/geerlingguy.apache`. In other words, the resulting directory structure would be:

```
content/geerlingguy.apache/
    defaults/
    handlers/
    meta/
    tasks/
    templates/
    tests/
```

##### ACTUAL RESULTS
Role was installed as `geerlingguy.geerlingguy.apache/roles/geerlingguy.apache`
